export { default as Navbar } from './Navbar';
export { default as Welcome } from './Welcome';
export { default as Experience } from './Experience';
export { default as Education } from './Education';
export { default as Qualifications } from './Qualifications';
export { default as Employments } from './Employments';
export { default as Trainings } from './Trainings';
export { default as Skills } from './Skills'
export { default as Contacts } from './Contacts'
export { default as Home } from './pages/Home'